/**
 * projects-data.js — corridor card content
 *
 * Spec   : C:\Users\art1\.claude\plans\quizzical-stirring-castle.md (Phase 3)
 * Source : arch-corridor-gallery/src/projectsData.ts
 *
 * 16 entries total: 10 oasis (אולם) + 6 lumina (ריזורט).
 * First 6 of each hall = verbatim Hebrew copy from the prototype.
 * The 4 extra oasis entries (07–10) are placeholder Hebrew — user will refine.
 *
 * Each entry is keyed by `id` so corridor cards reference it via
 * data-project-id="oasis-01" / "lumina-04". The drawer reads the full record.
 */

// ---------------------------------------------------------------------------
// OASIS — אולם (10 entries) → /assets/images/corridor/venue/{02,04,05,06,07,7_1,09,11,13,14}
// ---------------------------------------------------------------------------

const OASIS = [
  {
    id: "oasis-01",
    hallId: "oasis",
    number: "01",
    title: "היכל האואזיס • The Oasis Hall",
    subtitle: "סעודת גורמה תחת כיפת השמיים",
    category: "חוויית הסעודה",
    location: "מדבר יהודה, ישראל",
    year: "2026",
    color: "#E5D9C4",
    image: "/assets/images/corridor/venue/02.full.webp",
    imageJpg: "/assets/images/corridor/venue/02.full.jpg",
    description: "צילום ארכיטקטוני רחב ומרהיב של שולחנות עגולים רחבי ידיים תחת סככות פשתן מעוצבות, המשקיפים אל רכסי המדבר הזהובים. מרכזי שולחן עשירים של צמחייה פראית ונברשות קלועות המשרות אווירת יוקרה ראשונית.",
    details: [
      "הפרדה מושלמת בין גוני החול המוזהבים לגוני העץ הכהים.",
      "חיתוך קומפוזיציה חכם המדגיש את משחקי הפרספקטיבה של הסככות המעוצבות.",
      "פרטים קטנים ומטופלים השומרים על חדות לכל אורך קו השולחן המרכזי.",
    ],
    photoTitleHe: "סעודה תחת אהיל הפשתן במרחב הפתוח של המדבר",
    photoTitleEn: "A dining setup under linen shades in the vast open desert",
    photographer: "רון כהן • Ronen Cohen",
    camera: "Sony Alpha 7R V",
    lens: "24-70mm f/2.8 GM II",
    settings: "f/2.8 · ISO 100 · 1/160s · @35mm",
    lighting: "תאורת שקיעה מדברית זהובה וטבעית רכה המשתלבת עם תאורת נורות פחם חמימות התלויות ממעל.",
    composition: "קומפוזיציה קלאסית רחבה המדגישה קווים סימטריים של שולחנות עגולים תחת סככות פשתן אורגניות, עם עומק שדה רדוד המבליט את סידורי השולחן המרכזיים המרשימים.",
  },
  {
    id: "oasis-02",
    hallId: "oasis",
    number: "02",
    title: "סיפון המיראז' • The Mirage Deck",
    subtitle: "בריכת אינסוף ומיטות שיזוף מול הדיונות",
    category: "מתחם קבלת הפנים",
    location: "קדם נווה מדבר",
    year: "2026",
    color: "#DFD3C3",
    image: "/assets/images/corridor/venue/04.full.webp",
    imageJpg: "/assets/images/corridor/venue/04.full.jpg",
    description: "צילום סצנת הבריכה בסיפון עץ ארז הצף על גבי בריכת אינפיניטי צלולה, המשתקפת בגווני שמי השקיעה הכתומים. פינות רביצה מפוארות המאפשרות לאורחים להתנתק מהעולם ולהתחבר לשקט המוחלט של המדבר.",
    details: [
      "השתקפות סימטרית וחדה של הרי המדבר על פני המים השלווים.",
      "הולכת קווים מושלמת מהסיפון היישר אל שקיעת השמיים והמרחב האינסופי.",
      "ניגודיות מרהיבה בין המים בגווני הטורקיז לחיות החול הזהובה.",
    ],
    photoTitleHe: "בריכת אינפיניטי ומיטות שיזוף בשילוב הרי המדבר",
    photoTitleEn: "Infinity pool with sunbeds reflecting the desert mountains",
    photographer: "אמיר בר-לב • Amir Bar-Lev",
    camera: "Leica SL2",
    lens: "Summicron-SL 35mm f/2 ASPH",
    settings: "f/4.0 · ISO 200 · 1/320s · @35mm",
    lighting: "תאורת דמדומים אחרונה (Golden Hour) המשתקפת במים הצלולים ויוצרת גוון כחול עמוק מדויק משולב בסימת כתום עז מול השמיים המסמיקים.",
    composition: "זווית צילום נמוכה ודינמית המשתמשת בשולי הבריכה כקו מוליך אל מרחבי הדיונות האינסופיות הנפרסות ברקע.",
  },
  {
    id: "oasis-03",
    hallId: "oasis",
    number: "03",
    title: "במת המים • The Water Altar",
    subtitle: "חופה ארכיטקטונית צפה על המים",
    category: "מתחם החופה",
    location: "רחבת הבריכה המרכזית",
    year: "2026",
    color: "#F5EBE6",
    image: "/assets/images/corridor/venue/05.full.webp",
    imageJpg: "/assets/images/corridor/venue/05.full.jpg",
    description: "צילום המבנה והאדריכלות המקומית של חופה בעיצוב קשתות קלאסי ומרהיב הממוקם במרכז בריכת המים הגדולה. רשתות נחושת מעודנות ונברשות תלויות המשתלבות עם ההשתקפויות ליצירת רגעים בלתי נשכחים.",
    details: [
      "מיקוד בקשרים ובטקסטורות של המבנה המעוצב במרכז הבריכה.",
      "עומק שדה רחב המאפשר חדות מלאה של האורחים ברקע והאלמנטים הצפים.",
      "שימוש באור טבעי המדגיש את מרקם הבריזה במים והבדים הנשפכים.",
    ],
    photoTitleHe: "חופה צפה ובמת קשתות ארכיטקטונית",
    photoTitleEn: "Water altar floating ceremony pavilion and architecture",
    photographer: "מיה גלזר • Maya Glazer",
    camera: "Fujifilm GFX 100S",
    lens: "GF 45-100mm f/4 R LM OIS WR",
    settings: "f/5.6 · ISO 100 · 1/125s · @45mm",
    lighting: "תאורת ערב קולנועית (Ambient Blue Hour) עם הדגשות חמימות ייעודיות מתוך גופי תאורת לד שקועים מסביב לבמת השיש והשתקפויות המים הזוהרות.",
    composition: "צילום ריכוזי מול קשתות החופה, המשתמש בציר סימטרי מושלם של בריכת המים המרכזית ומשתקף בה להעצמת נפח הטקס האדריכלי.",
  },
  {
    id: "oasis-04",
    hallId: "oasis",
    number: "04",
    title: "קבלת פנים שקיעה • Sunset Reception",
    subtitle: "מתחם טקסים פנורמי תחת כיפת השמיים",
    category: "שטח פתוח למדבר",
    location: "חוקות השמיים",
    year: "2026",
    color: "#F6F5F2",
    image: "/assets/images/corridor/venue/06.full.webp",
    imageJpg: "/assets/images/corridor/venue/06.full.jpg",
    description: "צילום אמנותי רחב של סידורי ישיבה יוקרתיים מול קו האופק המדברי המשתנה עם רדת החשיכה. אהילים קלועים המשתלשלים ממתכת שחורה ארכיטקטונית יוצרים ניגודיות עוצרת נשימה בין הטבע הפראי ליוקרה מתוחכמת.",
    details: [
      "טווח דינמי עשיר (HDR) השומר על פרטי השקיעה העדינים ועל פרטי הצל באזורי הישיבה הכהים.",
      "הקפאה מדויקת של תנועת הבדים ברוח המדבר השלווה.",
      "קווים גיאומטריים של המתכות השחורות המנוגדים לעקמומיות הטבעית של הדיונות.",
    ],
    photoTitleHe: "כניסה מרהיבה וסידורי ישיבה תחת כיפת השמיים",
    photoTitleEn: "Breathtaking entrance and lounge alignments under the open sky",
    photographer: "ליאור שביט • Lior Shavit",
    camera: "Canon EOS R5",
    lens: "RF 15-35mm f/2.8L IS USM",
    settings: "f/2.8 · ISO 400 · 1/80s · @15mm",
    lighting: "ערבול צבעי שקיעה מדבריים דרמטיים, גוני סגול עז, ורוד וכתום. תאורה טבעית אחורית המשרה ניגודיות עוצמתית לפרטים ואהילי המתכת הכהים.",
    composition: "צילום בזווית רחבה מאוד (Ultra-Wide Angle), המעניקה פרספקטיבה עוטפת ומעצימה של גובה האהילים והקונסטרוקציות מול מרחבי המדבר השממים.",
  },
  {
    id: "oasis-05",
    hallId: "oasis",
    number: "05",
    title: "משתה המדבר • Desert Banquet",
    subtitle: "סעודת אבירים ארוכה בעיצוב ארצי מתוחכם",
    category: "חלל משתה אינטימי",
    location: "מתחם הקולונדה",
    year: "2026",
    color: "#EAE3D2",
    image: "/assets/images/corridor/venue/07.full.webp",
    imageJpg: "/assets/images/corridor/venue/07.full.jpg",
    description: "מיקוד תקריב אמנותי של שולחן אבירים ארוך ועשיר הפרוס מול הרי השממה, מעוטר בכלי חרס וקריסטלים ובדים טבעיים. שילוב הרמוני של גסטרונומיה יוקרתית מלווה ביינות מקומיים המיוצרים בכרמי הר הנגב.",
    details: [
      "הדגשת הטקסטורות הגסות של כלי החרס ועדינותם של גביעי הקריסטל המנצנצים.",
      "עומק שדה רדוד במיוחד (Bokeh) המעניק לשולחן זרימה תלת-ממדית מהפנטת.",
      "צבעוניות חמה של אדמה כחוויה קולינרית וחזותית מעודנת.",
    ],
    photoTitleHe: "שולחן אבירים במרקמים אורגניים",
    photoTitleEn: "Knight banquet table styled with raw organic textures and dinnerware",
    photographer: "דניאלה רוט • Daniella Roth",
    camera: "Hasselblad X2D 100C",
    lens: "XCD 55mm f/2.5",
    settings: "f/2.5 · ISO 64 · 1/200s · @55mm",
    lighting: "תאורה כיוונית צדדית רכה החודרת מבעד לפילטר טקסטיל קל ומאירה את השולחן באור שמדגיש את החומרים הגולמיים וכוסות הזכוכית.",
    composition: "צילום פורטרט-קונספט בגובה השולחן (Medium Close-Up) המתמקד בפרספקטיבה האורכית של אורך שולחן האבירים ובפרטים המדויקים המונחים עליו.",
  },
  {
    id: "oasis-06",
    hallId: "oasis",
    number: "06",
    title: "פרטי האומנות • Curated Details",
    subtitle: "ניואנסים מעודנים של עושר וטבע",
    category: "יצירת אומנות אירועים",
    location: "פנים וחוץ",
    year: "2026",
    color: "#F9F6F0",
    image: "/assets/images/corridor/venue/7_1.full.webp",
    imageJpg: "/assets/images/corridor/venue/7_1.full.jpg",
    description: "צילום מאקרו מרהיב של הפרטים הקטנים והמדויקים המגדירים את קדם: מפיות פשתן סרוגות ידנית, צלחות קרמיקה בעלות מרקם אורגני, כלי זכוכית מעוצבים וענפי דקל המעלים תחושת חמימות ויוקרה רוגעת.",
    details: [
      "צילום תקריב קיצוני החושף קפלים עדינים בפשתן המעומלן וסיבי החבל הדקים השזורים בו.",
      "מיקוד חד ומפוקס על שולי הצלחת שמגדיר את הטון והעיצוב הסופט.",
      "משחקי השתקפויות מן הזהב וסידור הפרחים היבש היוצרים הילה חלומית.",
    ],
    photoTitleHe: "מקרו של סידור השולחן ופרטי האומנות המעוצבים",
    photoTitleEn: "Macro design detail close-up showing custom stoneware and threads",
    photographer: "יונתן רז • Jonathan Raz",
    camera: "Sony Alpha 7R V",
    lens: "90mm f/2.8 Macro G OSS",
    settings: "f/2.8 · ISO 160 · 1/250s · @90mm",
    lighting: "תאורת שמש ישירה ורכה המתרכזת בזווית הצד ומשרטטת בדיוק רב את סיבי מפיות הפשתן הדקים ואריגי הקש המקשטים את סידור המקום.",
    composition: "צילום מאקרו (Extreme Close-Up) עם עומק שדה רדוד במיוחד המבודד בקפידה זווית אחת המדגישה טקסטורות גולמיות בלתי מעובדות.",
  },

  // ---- Placeholder entries (07–10) — user will refine copy later ----------
  {
    id: "oasis-07",
    hallId: "oasis",
    number: "07",
    title: "האולם הפנימי • The Inner Hall",
    subtitle: "חלל מרכזי בערב חגיגי",
    category: "חלל פנימי",
    location: "מתחם הזכוכית",
    year: "2026",
    color: "#E8DFD3",
    image: "/assets/images/corridor/venue/09.full.webp",
    imageJpg: "/assets/images/corridor/venue/09.full.jpg",
    description: "צילום החלל המרכזי של האולם בשעות הערב, עם תאורה דרמטית ותקרה בגובה כפול שיוצרים תחושת רוממות. המקום שבו האירוע הופך לזיכרון.",
    details: [
      "תאורה ארכיטקטונית מדויקת המעצבת את החלל מבפנים החוצה.",
      "טווח דינמי עשיר השומר גם על נקודות האור החזקות וגם על הפרטים בצללים.",
      "עיצוב שמדגיש גובה ופרספקטיבה מבלי לאבד את האינטימיות.",
    ],
    photoTitleHe: "החלל המרכזי בעיצומו של ערב",
    photoTitleEn: "The central hall at the height of an evening event",
    photographer: "—",
    camera: "—",
    lens: "—",
    settings: "—",
    lighting: "תאורה ארכיטקטונית עם נקודות חימום נקודתיות.",
    composition: "צילום סימטרי מאחור החלל לעבר במת הכבוד, מדגיש גובה ועומק.",
  },
  {
    id: "oasis-08",
    hallId: "oasis",
    number: "08",
    title: "רגעי האורחים • Guest Moments",
    subtitle: "התמונות שנשארות אחרי שהאורות נדלקים",
    category: "רגעי הערב",
    location: "פנים האולם",
    year: "2026",
    color: "#F0E8D8",
    image: "/assets/images/corridor/venue/11.full.webp",
    imageJpg: "/assets/images/corridor/venue/11.full.jpg",
    description: "אורחים חוגגים ברגעים המשמעותיים של הערב, המוקפים בעיצוב שתומך בלי להעיב.",
    details: [
      "צילום דוקומנטרי טהור הלוכד רגשות אמיתיים.",
      "פוקוס סלקטיבי המבליט פנים אנושיות מתוך החלל הצפוף.",
      "טמפרטורת צבע חמה השומרת על אווירה אינטימית.",
    ],
    photoTitleHe: "רגעי האורחים על הרחבה",
    photoTitleEn: "Guest moments on the dance floor",
    photographer: "—",
    camera: "—",
    lens: "—",
    settings: "—",
    lighting: "אור טבעי משולב עם פנס תאורה רך מהצד.",
    composition: "צילום קרוב פותח, מקרב את הצופה לחוויה.",
  },
  {
    id: "oasis-09",
    hallId: "oasis",
    number: "09",
    title: "לב הערב • Heart of the Night",
    subtitle: "כשהקירות מהדהדים שמחה",
    category: "אווירת לילה",
    location: "רחבת הריקודים",
    year: "2026",
    color: "#DFD3B8",
    image: "/assets/images/corridor/venue/13.full.webp",
    imageJpg: "/assets/images/corridor/venue/13.full.jpg",
    description: "השעות שבהן הזמן עוצר. הרחבה מלאה, המוזיקה גבוהה, האור נמוך, וכל אחד יודע למה הוא בא.",
    details: [
      "צילום ארוך-חשיפה הלוכד תנועה ועם זאת שומר על חדות בפנים מרכזיים.",
      "ניגודיות חזקה בין אזורי האור הפעיל לאזורי הצל המעטים.",
      "מסגור שמדגיש את גודל החלל מבלי לאבד את האירוע במרכזו.",
    ],
    photoTitleHe: "לב הערב על הרחבה",
    photoTitleEn: "Heart of the night on the dance floor",
    photographer: "—",
    camera: "—",
    lens: "—",
    settings: "—",
    lighting: "תאורת רחבה דינמית עם פנסים ייעודיים מהיציע.",
    composition: "מסגור רחב בגובה גבוה, לוכד את כל הקהל.",
  },
  {
    id: "oasis-10",
    hallId: "oasis",
    number: "10",
    title: "סיום הערב • End of the Night",
    subtitle: "השעות הראשונות, הזיכרון נשאר",
    category: "סיום הערב",
    location: "יציאה אל המדבר",
    year: "2026",
    color: "#E5D9C4",
    image: "/assets/images/corridor/venue/14.full.webp",
    imageJpg: "/assets/images/corridor/venue/14.full.jpg",
    description: "האורחים האחרונים יוצאים, האור מתחיל להחזיר את עצמו, והערב מתחיל להיות סיפור.",
    details: [
      "אווירת dawn light הלוכדת את המעבר מלילה לבוקר.",
      "צללים ארוכים ועדינים שיוצרים תחושת סוף.",
      "קומפוזיציה רוגעת אחרי האנרגיה של השעות הקודמות.",
    ],
    photoTitleHe: "סיום הערב, האורחים האחרונים",
    photoTitleEn: "End of the night, the last guests",
    photographer: "—",
    camera: "—",
    lens: "—",
    settings: "—",
    lighting: "אור טבעי של זריחה חדשה.",
    composition: "מסגור רחב, לוכד את התחושה השלווה של בוקר אחרי.",
  },
];


// ---------------------------------------------------------------------------
// LUMINA — ריזורט (6 entries) → /assets/images/corridor/resort/{4_1,05,10,14,15,17}
// ---------------------------------------------------------------------------

const LUMINA = [
  {
    id: "lumina-01",
    hallId: "lumina",
    number: "01",
    title: "תעלת האורות • The Dusk Canal",
    subtitle: "תמונת המדבר וחוג הספירות הזוהרות המשתקפות",
    category: "תערוכת דמדומים",
    location: "ציר המים המרכזי",
    year: "2026",
    color: "#FBBD23",
    image: "/assets/images/corridor/resort/4_1.full.webp",
    imageJpg: "/assets/images/corridor/resort/4_1.full.jpg",
    description: "צילום אמנותי מהפנט הלוקח השראה ישירה מעיצוב אקוודוקט המים האינסופי החוצה את המדבר, שלאורכו מונחות ספירות אור ענקיות וזוהרות המשתקפות במים ברוגע לצד שמי שקיעה בגווני זהב וארגמן.",
    details: [
      "עומק פרספקטיבה מושלמת עם קו מוליך של אקוודוקט מים מרהיב.",
      "ספירות אור המפיצות זוהר זהוב פוטו-מטרי עשיר המשוחזר בקפידה רבה.",
      "שילוב קוסמי של שמי חול חמים ודומיה מהפנטת לחלוטין ברקע.",
    ],
    photoTitleHe: "שדירת הספירות הזוהרות על ציר המים המדברי",
    photoTitleEn: "Endless desert water canal lined with glowing spherical lanterns",
    photographer: "ברק אלון • Barak Alon",
    camera: "Phase One XF IQ4",
    lens: "Schneider Kreuznach 35mm f/3.5",
    settings: "f/8.0 · ISO 50 · 0.5s · @35mm",
    lighting: "אור דמדומים טבעי זהוב-כתום מנוגד להילה החמימה והפועמת של ספירות הלד הממוקמות על קו המים.",
    composition: "פרספקטיבה חד-נקודתית המובלת מדויק למרכז העין בנתיב מים ארוך ומוזהב הנמשך עד האופק הצר בהרמוניה מוחלטת.",
  },
  {
    id: "lumina-02",
    hallId: "lumina",
    number: "02",
    title: "התרחבות הספירות • Floating Harmony",
    subtitle: "ספירות המדבר הצפות ומפזרות זוהר",
    category: "עיצוב תאורה סביבתית",
    location: "מתחם הספירות הזוהרות",
    year: "2026",
    color: "#E2A960",
    image: "/assets/images/corridor/resort/05.full.webp",
    imageJpg: "/assets/images/corridor/resort/05.full.jpg",
    description: "צילום תקריב החוקר את מופק האור של הספירות המדבריות, המונחות על חולות דקים וזהובים ומאירות את הצמחייה המדברית השברירית בטקסטורות עשירות המזכירות את גרמי השמיים.",
    details: [
      "פוקוס חד ביותר על מרקם הפני הדמוי גבס וחימר של כדור האור.",
      "החזר אור עדין על גבי גרגרי דיונת קדם המקורית.",
      "אפקט הדרגתי מרהיב הנע בין אבק כוכבים חולי לתאורת דאון-לייט חמה.",
    ],
    photoTitleHe: "ספירת אור במרקם מדבר ראשוני",
    photoTitleEn: "Glowing sand orbs scattering natural golden radiance on warm dunes",
    photographer: "ארז שגב • Erez Segev",
    camera: "Sony Alpha 7R V",
    lens: "FE 50mm f/1.2 GM",
    settings: "f/1.2 · ISO 100 · 1/250s · @50mm",
    lighting: "תאורה פנימית רכה וחמימה המעומעמת באופן דינמי לקבלת אפקט של נשימה קוסמית אמיתית.",
    composition: "קומפוזיציה חתוכה (Asymmetric Balance) הממקמת את הכדור בצידי הפריים ומאפשרת לצמחים וצללים לפעום בצירים רוחביים.",
  },
  {
    id: "lumina-03",
    hallId: "lumina",
    number: "03",
    title: "שער הדמדומים • The Dusk Portal",
    subtitle: "טבילה קוסמית של מים והשתקפויות שמיים",
    category: "חוויה פיזיקלית פנורמית",
    location: "הבריכה הדרומית",
    year: "2026",
    color: "#F6C592",
    image: "/assets/images/corridor/resort/10.full.webp",
    imageJpg: "/assets/images/corridor/resort/10.full.jpg",
    description: "סביבה מופשטת שבה חופת החול פוגשת השתקפות שמיים כחולים מעורבים בכתום שמימי. כדורי אור מעטרים את קצוות החלל וניצבים כמו מגדלורים מונחים בזעיר אנפין על פני המים.",
    details: [
      "הפרדת קו גבול מבריקה בין שמי המדבר למשקעי האגם.",
      "תאורה סביבתית המשלבת אלקטרוניקה מודרנית עם גבישי נוף ייחודיים.",
      "משחקי חום וקור המיוצגים בדיאלוג החזותי שבין הכחול הלילי לאור החם.",
    ],
    photoTitleHe: "מגדלורי אור ומבני מראות בהיכל הדמדומים",
    photoTitleEn: "Dusk reflections and cosmic visual anchors at the southern pond",
    photographer: "עדי מור • Adi Mor",
    camera: "Fujifilm GFX 100S",
    lens: "GF 32-64mm f/4 R LM WR",
    settings: "f/5.6 · ISO 250 · 1/60s · @32mm",
    lighting: "פנייה אל האור הטבעי של שעת המעבר הכחולה המאוזנת על ידי דיודות ניאון חמימות המותקנות בפינות ובתוך אריחי הספירות.",
    composition: "צילום מזווית נמוכה ליד האדוות ליצירת רצף קווי תנופת מים מושלמים.",
  },
  {
    id: "lumina-04",
    hallId: "lumina",
    number: "04",
    title: "אופקים זוהרים • Glowing Horizons",
    subtitle: "נוף הרי המדבר מאחורי כדורי הזוהר",
    category: "תפר קדוש ואדריכלות",
    location: "חמוקי הדיונה",
    year: "2026",
    color: "#E5CAB0",
    image: "/assets/images/corridor/resort/14.full.webp",
    imageJpg: "/assets/images/corridor/resort/14.full.jpg",
    description: "צילום ממרחק הלוכד מגוון כדורים מאירים הפזורים בקניון המרהיב המורכב מסלעי גיר זהובים, כשהמרחב נראה כחלום של נווה מדבר עתידני ועמוס מיסתורין מנחם.",
    details: [
      "חדות קצה מוחלטת מראש ועד תחתית הרי הגיר והמדרונות.",
      "נחיתה דרמטית של צללים ארוכים של סוף היום המדגישים את הדינמיות של פני השטח.",
      "שיוך הרמוני של גלי האור הטכנולוגיים אל הטופוגרפיה הפיזית ההררית.",
    ],
    photoTitleHe: "נווה מדבר עתידני בחמוקי הסלעים של קדם",
    photoTitleEn: "Lumina orbs integrated into the ancient desert limestone valleys",
    photographer: "יואב גל • Yoav Gal",
    camera: "Leica M11",
    lens: "Apo-Summicron-M 50mm f/2 ASPH",
    settings: "f/4.0 · ISO 64 · 1/125s · @50mm",
    lighting: "שילוב בין השמש השוקעת מאחורי הרכס לבין אלומות האור העגולות של הציוד הסביבתי המשעשע.",
    composition: "צילום עומק רב-שכבתי (Foreground-Midground-Background) המוליך את העין בשרשרת כדורים עד להרים הרחוקים.",
  },
  {
    id: "lumina-05",
    hallId: "lumina",
    number: "05",
    title: "הגסטרונומיה הזוהרת • Lumina Feast",
    subtitle: "חווית סעודה מוקפת בספירות חמימות",
    category: "חווית הסעודה",
    location: "מתחם האקוודוקט השקט",
    year: "2026",
    color: "#CFB092",
    image: "/assets/images/corridor/resort/15.full.webp",
    imageJpg: "/assets/images/corridor/resort/15.full.jpg",
    description: "צילום שולחנות משתה מהודרים הניצבים לצד שביל המים והכדורים הזוהרים. כלי קריסטל וחרס זהובים לוכדים את הניצוצות המשתקפים מהספירות ליצירת סביבה יוקרתית עוצרת נשימה.",
    details: [
      "משחקי אור אינסופיים בגזרת כלי הקריסטל והיוקרה התלויים והפרוסים.",
      "פלטת צבעים המשלבת אמבר, דבש ואינדיגו לילי עמוק.",
      "חשיפת החול המדויקת המחברת בין עיצוב השולחן המוקפד לראשוניות השטח.",
    ],
    photoTitleHe: "סעודת גורמה מוקפת פעימות אור של ספירות",
    photoTitleEn: "A high-end fine-dining design surrounded by glowing spheres",
    photographer: "ארז שגב • Erez Segev",
    camera: "Hasselblad H6D-100c",
    lens: "HC 80mm f/2.8",
    settings: "f/4.0 · ISO 100 · 1/180s · @80mm",
    lighting: "תאורה כפולה עוטפת המורכבת משמי זהב רכים והילה נמוכה מהמנורות הסביבתיות.",
    composition: "מנח צדדי אלכסוני המעניק זרימה ועושר ייחודי עבור פינות הישיבה היוקרתיות החדשות במתחם.",
  },
  {
    id: "lumina-06",
    hallId: "lumina",
    number: "06",
    title: "חלקיקי הזוהר • Celestial Textures",
    subtitle: "פרטי העיצוב המהפנטים של האולם השני",
    category: "יצירת אומנות אירועים",
    location: "חלל פנים וחוץ בעיצוב ספירות",
    year: "2026",
    color: "#DFCEBE",
    image: "/assets/images/corridor/resort/17.full.webp",
    imageJpg: "/assets/images/corridor/resort/17.full.jpg",
    description: "צילום תקריב החושף את הפרטים של סידורי החלל הייחודיים להיכל השני: מנורות אמבר קטנות מונחות בקערות חרס, סיבי כותנה טבעיים ופיגמנטים של אדמת המדבר המוזהבת.",
    details: [
      "מאקרו מרהיב של פליטת חום ענברית מתוך אלמנטי זכוכית נושמת שנוצרו בעבודת יד.",
      "הפרדת צבעים נהדרת המשמרת את היוקרה השקטה והעיצוב הסולידי.",
      "שימור המרקם הגרגרי של החרס בהולכת עין ישירה המשרה רוגע.",
    ],
    photoTitleHe: "פרטי זכוכית אמנותיים וחרס מעוצב",
    photoTitleEn: "Artistic handmade glass filters and earthy ceramics at the Lumina Altar",
    photographer: "מיה גלזר • Maya Glazer",
    camera: "Sony Alpha 7R V",
    lens: "90mm f/2.8 Macro G OSS",
    settings: "f/2.8 · ISO 200 · 1/160s · @90mm",
    lighting: "נקודת שמש חודרת אחורית המייצרת תאורת רים (Rim Light) מוזהבת המקדשת את קצוות החפצים והכלים.",
    composition: "צילום קלוז-אפ מוקפד המעלה ניגודיות נהדרת ויוקרה של חומר גלמי.",
  },
];


// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export const PROJECTS = {
  oasis: OASIS,
  lumina: LUMINA,
};

const BY_ID = new Map();
for (const list of [OASIS, LUMINA]) {
  for (const p of list) BY_ID.set(p.id, p);
}

export function getProjectById(id) {
  return BY_ID.get(id) || null;
}
