import type { Project, ExtractedColors, ProjectWithColors } from "./types";
// extractedColors.json is generated by scripts/extract-colors.mjs (Wave B):
// one entry per image path with { background, blob1, blob2 } sampled from
// each WebP. Re-run that script whenever images/projects/ changes. If a
// path is missing from the JSON, getProjectsByHall() falls back to
// FALLBACK_COLORS (brand palette).
import extractedColors from "./data/extractedColors.json";

// Warm-luxury fallback (Wave 5). Used only when a plane image is absent from
// extractedColors.json. Biased to the Gamos palette (ivory-warm ground + brass
// / cocoa blobs) so a missing extraction degrades into the warm skin rather
// than the reference's dark icy aesthetic — keeps the GLSL background
// continuous with the main site even before any per-image mood lands.
const FALLBACK_COLORS: ExtractedColors = {
  background: "#ece3d3", // ivory-warm
  blob1: "#cfae83", // brass
  blob2: "#534133", // cocoa
};

export const projectsData: Project[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // HALL 1: EVENTS HALL (אולם האירועים)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "events-hall",
    hallId: "events",
    number: "01",
    title: "שדרת השערים",
    subtitle: "מעבר הקשתות המוזהבות אל גן האירועים",
    label: "שדרת הקשתות המוזהבות בגן",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-01.webp",
  },
  {
    id: "mirage-deck",
    hallId: "events",
    number: "02",
    title: "טרסת קבלת הפנים",
    subtitle: "פינות ישיבה בין עצים מעוצבים בשעת בין הערביים",
    label: "טרסת קבלת הפנים בין העצים",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-02.webp",
  },
  {
    id: "floating-pavilion",
    hallId: "events",
    number: "03",
    title: "חצר האבן",
    subtitle: "קיר טקסטורה מואר וקשת מוזהבת בכניסה לחלל",
    label: "חצר האבן והקשת המוזהבת",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-04.webp",
  },
  {
    id: "sunset-ceremony",
    hallId: "events",
    number: "04",
    title: "הטיילת בשקיעה",
    subtitle: "טיילת ארוכה עם פינות ישיבה לאורך קו הגן",
    label: "טיילת הגן בשעת השקיעה",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-06.webp",
  },
  {
    id: "desert-banquet",
    hallId: "events",
    number: "05",
    title: "הבר המרכזי",
    subtitle: "בר אבן פתוח עם תאורה חמה תחת סככת מתכת",
    label: "הבר המרכזי של הגן",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-08.webp",
  },
  {
    id: "curated-details",
    hallId: "events",
    number: "06",
    title: "החופה בגן",
    subtitle: "חופת עמודים לבנה מול קיר הירק והגן הפתוח",
    label: "החופה הלבנה בגן הפתוח",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-10.webp",
  },
  {
    id: "grand-arrival",
    hallId: "events",
    number: "07",
    title: "כיכר הכניסה",
    subtitle: "רחבת אבן רחבה מול חזית הזכוכית של האולם",
    label: "כיכר הכניסה מול חזית האולם",
    location: "האולם הראשי",
    year: "2026",
    image: "images/projects/events-09.webp",
  },
  {
    id: "stone-promenade",
    hallId: "events",
    number: "08",
    title: "רחבת הבר והעצים",
    subtitle: "המרחב הפתוח שבין הבר, העצים והאולם",
    label: "רחבת הבר והעצים המעוצבים",
    location: "גן האירועים",
    year: "2026",
    image: "images/projects/events-05.webp",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // HALL 2: RESORT (ריזורט המדבר)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "resort-canal",
    hallId: "resort",
    number: "01",
    title: "בריכת OASIS בשקיעה",
    subtitle: "בריכת האינסוף וחופת הקשתות מול הרי המדבר",
    label: "בריכת OASIS מול הרי המדבר",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-01.webp",
  },
  {
    id: "floating-harmony",
    hallId: "resort",
    number: "02",
    title: "החופה על המים",
    subtitle: "חופת קשתות לבנה הניצבת על פני בריכת OASIS",
    label: "חופת הקשתות על בריכת OASIS",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-02.webp",
  },
  {
    id: "dusk-reflection",
    hallId: "resort",
    number: "03",
    title: "האולם המקורה",
    subtitle: "חלל אירוח מקורה עם נברשות קש ונוף מדבר",
    label: "האולם המקורה של הריזורט",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-03.webp",
  },
  {
    id: "glowing-horizons",
    hallId: "resort",
    number: "04",
    title: "שולחן מול המדבר",
    subtitle: "שולחן ערוך לאורך הטרסה הפתוחה אל הרי יהודה",
    label: "שולחן הסעודה מול הרי יהודה",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-04.webp",
  },
  {
    id: "resort-banquet",
    hallId: "resort",
    number: "05",
    title: "סעודה על הטרסה",
    subtitle: "ערכת שולחן מוקפדת בשעת בין הערביים המדברית",
    label: "סעודה על הטרסה בבין הערביים",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-05.webp",
  },
  {
    id: "celestial-textures",
    hallId: "resort",
    number: "06",
    title: "אולם העגול",
    subtitle: "שולחנות עגולים ונברשות תחת תקרת הריזורט",
    label: "אולם השולחנות העגולים",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-06.webp",
  },
  {
    id: "twin-orbs",
    hallId: "resort",
    number: "07",
    title: "נוף הרי המדבר",
    subtitle: "מרחבי הרי יהודה הנשקפים מהריזורט",
    label: "נוף הרי המדבר מהריזורט",
    location: "מישור אדומים",
    year: "2026",
    image: "images/projects/resort-07.webp",
  },
  {
    id: "infinity-mirror",
    hallId: "resort",
    number: "08",
    title: "בריכת האינסוף",
    subtitle: "מי הבריכה הנשפכים אל קו האופק של המדבר",
    label: "בריכת האינסוף מול האופק",
    location: "הריזורט",
    year: "2026",
    image: "images/projects/resort-08.webp",
  },
];

export function getProjectsByHall(hallId: "events" | "resort"): ProjectWithColors[] {
  const colorMap = extractedColors as Record<string, ExtractedColors>;
  return projectsData
    .filter((p) => p.hallId === hallId)
    .map((p) => ({ ...p, colors: colorMap[p.image] ?? FALLBACK_COLORS }));
}
