import type { Project, ExtractedColors, ProjectWithColors } from "./types";
// extractedColors.json is generated by scripts/extract-colors.mjs (Wave B):
// one entry per image path with { background, blob1, blob2 } sampled from
// each WebP. Re-run that script whenever images/projects/ changes. If a
// path is missing from the JSON, getProjectsByHall() falls back to
// FALLBACK_COLORS (brand palette).
import extractedColors from "./data/extractedColors.json";

// Warm-luxury fallback (Wave 5). Used only when a plane image is absent from
// extractedColors.json. Biased to the Gamos palette (ivory-warm ground + brass
// / cocoa blobs) so a missing extraction degrades into the warm skin rather
// than the reference's dark icy aesthetic — keeps the GLSL background
// continuous with the main site even before any per-image mood lands.
const FALLBACK_COLORS: ExtractedColors = {
  background: "#ece3d3", // ivory-warm
  blob1: "#cfae83", // brass
  blob2: "#534133", // cocoa
};

// 2026-06-17: re-curated full image set (user: "include all"). EVENTS = 32
// planes (from "אולם"), RESORT = 25 planes (from "ריזורט"). Each plane's caption
// is written to the specific photo it shows. CHUPPAH (חופה) photos are ordered
// LAST within each hall (user rule). Images map to halls/public/images/projects/
// <hall>-NN.webp, encoded from assets/_src/{events,resort} by `npm run encode:images`.
export const projectsData: Project[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // HALL 1: EVENTS HALL (אולם האירועים) — 32 planes (chuppahs 27–32)
  // ─────────────────────────────────────────────────────────────────────────
  { id: "events-01", hallId: "events", number: "01", title: "האולם הגדול", subtitle: "החלל הראשי המואר בנברשות קריסטל וסמל הבית על הקיר", label: "האולם הגדול עטור הנברשות", location: "האולם הראשי", year: "2026", image: "images/projects/events-01.webp" },
  { id: "events-02", hallId: "events", number: "02", title: "מזרקת השיש", subtitle: "מזרקת אבן מרכזית תחת נברשות הקריסטל לצד רחבת הריקודים", label: "מזרקת השיש תחת הנברשות", location: "האולם הראשי", year: "2026", image: "images/projects/events-02.webp" },
  { id: "events-03", hallId: "events", number: "03", title: "שדרת הקשתות", subtitle: "מעבר הקשתות המוזהבות המעוגלות מעל שביל הגן בשעת הזהב", label: "שדרת הקשתות המוזהבות", location: "גן האירועים", year: "2026", image: "images/projects/events-03.webp" },
  { id: "events-04", hallId: "events", number: "04", title: "מנהרת הקשתות", subtitle: "מנהרת הקשתות המוזהבות הנפתחת אל לב הגן הפורח", label: "מנהרת הקשתות אל הגן", location: "גן האירועים", year: "2026", image: "images/projects/events-04.webp" },
  { id: "events-05", hallId: "events", number: "05", title: "קשתות הזהב", subtitle: "הקשתות המוזהבות מובילות אל הלאונג' בשעת השקיעה", label: "קשתות הזהב בשעת השקיעה", location: "גן האירועים", year: "2026", image: "images/projects/events-05.webp" },
  { id: "events-06", hallId: "events", number: "06", title: "חצר עץ הזית", subtitle: "עץ זית מרכזי מול חזית הזכוכית של האולם באור הבוקר", label: "חצר עץ הזית בזריחה", location: "גן האירועים", year: "2026", image: "images/projects/events-06.webp" },
  { id: "events-07", hallId: "events", number: "07", title: "מרפסת הזכוכית", subtitle: "עץ הזית והמרפסת הפתוחה מול חזית הזכוכית הרחבה", label: "מרפסת הזכוכית הפתוחה", location: "גן האירועים", year: "2026", image: "images/projects/events-07.webp" },
  { id: "events-08", hallId: "events", number: "08", title: "חזית האולם", subtitle: "חזית האולם, הבר החיצוני ועצי הזית המעוצבים בכניסה", label: "חזית האולם ועצי הזית", location: "גן האירועים", year: "2026", image: "images/projects/events-08.webp" },
  { id: "events-09", hallId: "events", number: "09", title: "טיילת הלאונג'", subtitle: "טיילת הגן המוזהבת עם קשת הזהב המובילה אל הלאונג'", label: "טיילת הלאונג' המוזהבת", location: "גן האירועים", year: "2026", image: "images/projects/events-09.webp" },
  { id: "events-10", hallId: "events", number: "10", title: "פינות הגן", subtitle: "מרפסת לבנים, כורסאות נצרים ועץ פורח בפינות הישיבה", label: "פינות הישיבה בגן", location: "גן האירועים", year: "2026", image: "images/projects/events-10.webp" },
  { id: "events-11", hallId: "events", number: "11", title: "קשת הזהב", subtitle: "קשת הזהב המעוגלת לצד המרפסת הפתוחה אל הגן", label: "קשת הזהב לצד המרפסת", location: "גן האירועים", year: "2026", image: "images/projects/events-11.webp" },
  { id: "events-12", hallId: "events", number: "12", title: "לאונג' הגן", subtitle: "לאונג' הגן בגווני הסתיו עם פינות ישיבה רכות", label: "לאונג' הסתיו בגן הגג", location: "גן האירועים", year: "2026", image: "images/projects/events-12.webp" },
  { id: "events-13", hallId: "events", number: "13", title: "בר המשקאות", subtitle: "בר המשקאות הפתוח עם תאורה חמה בקצה הגן", label: "בר המשקאות הפתוח", location: "גן האירועים", year: "2026", image: "images/projects/events-13.webp" },
  { id: "events-14", hallId: "events", number: "14", title: "הבר בשקיעה", subtitle: "הבר הפתוח לצד עץ הזית המעוצב בשעת בין הערביים", label: "הבר ועץ הזית בשקיעה", location: "גן האירועים", year: "2026", image: "images/projects/events-14.webp" },
  { id: "events-15", hallId: "events", number: "15", title: "במת הזוג", subtitle: "במת הזוג ומגדלי האור הזוהרים בלב הקבלה", label: "במת הזוג והנברשות המוארות", location: "האולם הראשי", year: "2026", image: "images/projects/events-15.webp" },
  { id: "events-16", hallId: "events", number: "16", title: "שולחנות הנרות", subtitle: "שולחנות הסעודה המוארים בנרות ופמוטי כסף", label: "שולחנות מוארים בנרות", location: "האולם הראשי", year: "2026", image: "images/projects/events-16.webp" },
  { id: "events-17", hallId: "events", number: "17", title: "שולחן הקריסטל", subtitle: "שולחן ערוך בפמוטי קריסטל מול קיר אמנות מואר", label: "ערוך השולחן הקריסטלי", location: "האולם הראשי", year: "2026", image: "images/projects/events-17.webp" },
  { id: "events-18", hallId: "events", number: "18", title: "פרחים תלויים", subtitle: "סידור פרחים תלוי ומרהיב מעל שולחן הסעודה הארוך", label: "סידור פרחים תלוי מעל השולחן", location: "האולם הראשי", year: "2026", image: "images/projects/events-18.webp" },
  { id: "events-19", hallId: "events", number: "19", title: "שולחן הכלה", subtitle: "שולחן הכלה הפרחוני תחת קרני האור הרכות", label: "שולחן הכלה הפרחוני", location: "האולם הראשי", year: "2026", image: "images/projects/events-19.webp" },
  { id: "events-20", hallId: "events", number: "20", title: "פמוטי הקריסטל", subtitle: "שורת פמוטי קריסטל ונברשת בריקוד האור של הערב", label: "פמוטי הקריסטל בריקוד האור", location: "האולם הראשי", year: "2026", image: "images/projects/events-20.webp" },
  { id: "events-21", hallId: "events", number: "21", title: "שולחן הוורד", subtitle: "שולחן ערוך בגווני ורד רכים באור היום", label: "ערוך שולחן בגווני ורד", location: "האולם הראשי", year: "2026", image: "images/projects/events-21.webp" },
  { id: "events-22", hallId: "events", number: "22", title: "שולחן הגן", subtitle: "שולחן ערוך בענפי פריחה מול קיר הגן הירוק", label: "שולחן ערוך מול הגן", location: "גן האירועים", year: "2026", image: "images/projects/events-22.webp" },
  { id: "events-23", hallId: "events", number: "23", title: "שולחן העץ", subtitle: "שולחן עץ ערוך בפמוטים ופמפס קריסטל לבן", label: "שולחן העץ והפמוטים", location: "האולם הראשי", year: "2026", image: "images/projects/events-23.webp" },
  { id: "events-24", hallId: "events", number: "24", title: "קישוטי הפרח", subtitle: "כדורי פרחים ירוקים תלויים באור הזהב של האולם", label: "קישוטי הפרח הירוקים באולם", location: "האולם הראשי", year: "2026", image: "images/projects/events-24.webp" },
  { id: "events-25", hallId: "events", number: "25", title: "מתחם הקבלה", subtitle: "מיצב הישיבה מענפים עם סמל GAMOS על קיר הלבנים", label: "מתחם הקבלה של GAMOS", location: "גן האירועים", year: "2026", image: "images/projects/events-25.webp" },
  { id: "events-26", hallId: "events", number: "26", title: "במת היריעות", subtitle: "במת הזוג תחת יריעות בד וספה רכה ונברשות פרחים", label: "במת הזוג תחת היריעות", location: "האולם הראשי", year: "2026", image: "images/projects/events-26.webp" },
  // ── CHUPPAHS (חופות) — ordered last ──
  { id: "events-27", hallId: "events", number: "27", title: "חופת הקשת", subtitle: "חופת קשת לבנה מסורגת על רקע קיר הירק בגן", label: "חופת הקשת הלבנה בגן", location: "גן האירועים", year: "2026", image: "images/projects/events-27.webp" },
  { id: "events-28", hallId: "events", number: "28", title: "חופת הפנסים", subtitle: "חופת יריעות לבנה ושביל פנסים בלב הגן", label: "חופת היריעות והפנסים", location: "גן האירועים", year: "2026", image: "images/projects/events-28.webp" },
  { id: "events-29", hallId: "events", number: "29", title: "חופת המדבר", subtitle: "חופת יריעות לבנה ופמפס מול קו האופק המדברי", label: "חופת היריעות מול המדבר", location: "גן האירועים", year: "2026", image: "images/projects/events-29.webp" },
  { id: "events-30", hallId: "events", number: "30", title: "חופת העמודים", subtitle: "חופת עמודים לבנה ונברשת קריסטל בשעת בין הערביים", label: "חופת העמודים והנברשת", location: "גן האירועים", year: "2026", image: "images/projects/events-30.webp" },
  { id: "events-31", hallId: "events", number: "31", title: "חופת השיש", subtitle: "חופת עמודים קלאסית לבנה ונברשת מעל מעבר הכיסאות", label: "חופת השיש הקלאסית", location: "גן האירועים", year: "2026", image: "images/projects/events-31.webp" },
  { id: "events-32", hallId: "events", number: "32", title: "חופת השקיעה", subtitle: "חופת עמודים לבנה מול מעבר נרות בשעת השקיעה", label: "חופת העמודים בשקיעה", location: "גן האירועים", year: "2026", image: "images/projects/events-32.webp" },

  // ─────────────────────────────────────────────────────────────────────────
  // HALL 2: RESORT (ריזורט המדבר) — 25 planes (chuppahs 20–25)
  // ─────────────────────────────────────────────────────────────────────────
  { id: "resort-01", hallId: "resort", number: "01", title: "אולם הריזורט", subtitle: "אולם מקורה מפואר עם נברשות קריסטל ושביל לבן אל המדבר", label: "אולם הריזורט מול המדבר", location: "הריזורט", year: "2026", image: "images/projects/resort-01.webp" },
  { id: "resort-02", hallId: "resort", number: "02", title: "מבט על המתחם", subtitle: "מבט מלמעלה על המתחם, השולחנות ובריכת האינסוף", label: "מבט-על על המתחם והבריכה", location: "הריזורט", year: "2026", image: "images/projects/resort-02.webp" },
  { id: "resort-03", hallId: "resort", number: "03", title: "בריכת האינסוף", subtitle: "בריכת אינסוף, מיטות שיזוף ופרגולת עץ אל מרחבי המדבר", label: "בריכת האינסוף אל המדבר", location: "הריזורט", year: "2026", image: "images/projects/resort-03.webp" },
  { id: "resort-04", hallId: "resort", number: "04", title: "הבריכה והמדבר", subtitle: "בריכה ומיטות שיזוף תחת הפרגולה מול הדיונות", label: "בריכה ומדבר תחת הפרגולה", location: "הריזורט", year: "2026", image: "images/projects/resort-04.webp" },
  { id: "resort-05", hallId: "resort", number: "05", title: "מימי הבריכה", subtitle: "נוף המדבר ממוסגר בעמודי הפרגולה מעל מי הבריכה בדמדומים", label: "נוף המדבר ממימי הבריכה", location: "הריזורט", year: "2026", image: "images/projects/resort-05.webp" },
  { id: "resort-06", hallId: "resort", number: "06", title: "טרקלין היוקרה", subtitle: "ספות וכורסאות טרקלין מול הבריכה ונוף המדבר", label: "טרקלין יוקרה אל הנוף", location: "הריזורט", year: "2026", image: "images/projects/resort-06.webp" },
  { id: "resort-07", hallId: "resort", number: "07", title: "גלריית הקשתות", subtitle: "מרפסת שיש, ישיבה לבנה ומסכי נחושת מסורגים", label: "מרפסת וגלריית הקשתות", location: "הריזורט", year: "2026", image: "images/projects/resort-07.webp" },
  { id: "resort-08", hallId: "resort", number: "08", title: "בין הערביים", subtitle: "שביל מרכזי אל הקשת ונברשות מקרמה בשעת הדמדומים", label: "המתחם בשעת בין-ערביים", location: "הריזורט", year: "2026", image: "images/projects/resort-08.webp" },
  { id: "resort-09", hallId: "resort", number: "09", title: "שולחן החתן", subtitle: "שולחן ארוך עם קאלות וקיר LED של GAMOS מול הדיונות", label: "שולחן החתן מול המדבר", location: "הריזורט", year: "2026", image: "images/projects/resort-09.webp" },
  { id: "resort-10", hallId: "resort", number: "10", title: "שולחנות הטרקלין", subtitle: "שולחנות ערוכים בקאלות לבנות מול קיר הסריג", label: "שולחנות ערוכים בטרקלין", location: "הריזורט", year: "2026", image: "images/projects/resort-10.webp" },
  { id: "resort-11", hallId: "resort", number: "11", title: "פליז וקטיפה", subtitle: "כיסאות פליז וקטיפה, שולחנות ועצי דקל לצד קיר הסריג", label: "ערכת שולחנות פליז וקטיפה", location: "הריזורט", year: "2026", image: "images/projects/resort-11.webp" },
  { id: "resort-12", hallId: "resort", number: "12", title: "פריחה אל הנוף", subtitle: "פריחה בקדמת התמונה ושולחנות הסעודה אל הקשת והמדבר", label: "פריחה ושולחנות אל הנוף", location: "הריזורט", year: "2026", image: "images/projects/resort-12.webp" },
  { id: "resort-13", hallId: "resort", number: "13", title: "קאלות הבריכה", subtitle: "גבעולי קאלה לאורך השולחן מול הבריכה באור הדמדומים", label: "קאלות מול בריכת הריזורט", location: "הריזורט", year: "2026", image: "images/projects/resort-13.webp" },
  { id: "resort-14", hallId: "resort", number: "14", title: "פרחים ונרות", subtitle: "סידור קאלה וורדים בורוד, נרות ומבער חימום אינטימי", label: "סידור פרחים ונרות אינטימי", location: "הריזורט", year: "2026", image: "images/projects/resort-14.webp" },
  { id: "resort-15", hallId: "resort", number: "15", title: "קאלות השקיעה", subtitle: "קאלות וורדים גבוהים על רקע שמי שקיעה רכים", label: "קאלות ושמי שקיעה", location: "הריזורט", year: "2026", image: "images/projects/resort-15.webp" },
  { id: "resort-16", hallId: "resort", number: "16", title: "זר הקאלות", subtitle: "סידור קאלה וורדים מרכזי, ערכת שולחן וקיר GAMOS", label: "זר קאלות ושולחן ערוך", location: "הריזורט", year: "2026", image: "images/projects/resort-16.webp" },
  { id: "resort-17", hallId: "resort", number: "17", title: "כלי הבדולח", subtitle: "ערכת שולחן קרובה עם כלי בדולח נוצצים", label: "ערכת שולחן וכלי בדולח", location: "הריזורט", year: "2026", image: "images/projects/resort-17.webp" },
  { id: "resort-18", hallId: "resort", number: "18", title: "שולחן החצר", subtitle: "שולחן עגול ערוך וסידור ערבה בחצר המדבר", label: "שולחן עגול בחצר המדבר", location: "הריזורט", year: "2026", image: "images/projects/resort-18.webp" },
  { id: "resort-19", hallId: "resort", number: "19", title: "פשתן טבעי", subtitle: "ערכת שולחן בגווני פשתן טבעי, כלי זכוכית ועצי דקל", label: "ערכת שולחן ופשתן טבעי", location: "הריזורט", year: "2026", image: "images/projects/resort-19.webp" },
  // ── CHUPPAHS (חופות) — ordered last ──
  { id: "resort-20", hallId: "resort", number: "20", title: "חופת הפרחים", subtitle: "חופת פרחים לבנה ופורחת ועמודים מעוטרים מול המדבר", label: "חופת הפרחים אל המדבר", location: "הריזורט", year: "2026", image: "images/projects/resort-20.webp" },
  { id: "resort-21", hallId: "resort", number: "21", title: "חופת הנוצות", subtitle: "חופת פמפס ונוצות, יריעות לבנות בשעת השקיעה הזהובה", label: "חופת הנוצות בשקיעה הזהובה", location: "הריזורט", year: "2026", image: "images/projects/resort-21.webp" },
  { id: "resort-22", hallId: "resort", number: "22", title: "חופת הירח", subtitle: "חופת פרחים לבנה, מעבר וישיבת קוקון תחת אור הירח", label: "חופה לבנה תחת הירח", location: "הריזורט", year: "2026", image: "images/projects/resort-22.webp" },
  { id: "resort-23", hallId: "resort", number: "23", title: "חופת הבריכה", subtitle: "חופה לבנה עטורת פרחים מעל הבריכה מול הדיונות באור יום", label: "חופה צחורה מול הבריכה", location: "הריזורט", year: "2026", image: "images/projects/resort-23.webp" },
  { id: "resort-24", hallId: "resort", number: "24", title: "חופת המשי", subtitle: "יריעות משי לבנות וכתר פרחים לצד הבריכה", label: "חופת משי לצד הבריכה", location: "הריזורט", year: "2026", image: "images/projects/resort-24.webp" },
  { id: "resort-25", hallId: "resort", number: "25", title: "חופת הקריסטל", subtitle: "חופת פרחים ונברשת קריסטל על רצפת מראה מול המדבר", label: "חופת הקריסטל על רצפת המראה", location: "הריזורט", year: "2026", image: "images/projects/resort-25.webp" },
];

export function getProjectsByHall(hallId: "events" | "resort"): ProjectWithColors[] {
  const colorMap = extractedColors as Record<string, ExtractedColors>;
  return projectsData
    .filter((p) => p.hallId === hallId)
    .map((p) => ({ ...p, colors: colorMap[p.image] ?? FALLBACK_COLORS }));
}
