import type { Project, ExtractedColors, ProjectWithColors } from "./types";
// extractedColors.json is generated by scripts/extract-colors.mjs (Wave B):
// one entry per image path with { background, blob1, blob2 } sampled from
// each WebP. Re-run that script whenever images/projects/ changes. If a
// path is missing from the JSON, getProjectsByHall() falls back to
// FALLBACK_COLORS (brand palette).
import extractedColors from "./data/extractedColors.json";

// Warm-luxury fallback (Wave 5). Used only when a plane image is absent from
// extractedColors.json. Biased to the Gamos palette (ivory-warm ground + brass
// / cocoa blobs) so a missing extraction degrades into the warm skin rather
// than the reference's dark icy aesthetic — keeps the GLSL background
// continuous with the main site even before any per-image mood lands.
const FALLBACK_COLORS: ExtractedColors = {
  background: "#ece3d3", // ivory-warm
  blob1: "#cfae83", // brass
  blob2: "#534133", // cocoa
};

export const projectsData: Project[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // HALL 1: OASIS HALL (היכל האואזיס)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "oasis-hall",
    hallId: "oasis",
    number: "01",
    title: "היכל האואזיס • The Oasis Hall",
    subtitle: "סעודת גורמה תחת כיפת השמיים",
    label: "סעודת גורמה תחת כיפת השמיים",
    location: "מדבר יהודה, ישראל",
    year: "2026",
    image: "images/projects/oasis-01.webp",
  },
  {
    id: "mirage-deck",
    hallId: "oasis",
    number: "02",
    title: "סיפון המיראז' • The Mirage Deck",
    subtitle: "בריכת אינסוף ומיטות שיזוף מול הדיונות",
    label: "בריכת אינסוף ומיטות שיזוף מול הדיונות",
    location: "קדם נווה מדבר",
    year: "2026",
    image: "images/projects/oasis-02.webp",
  },
  {
    id: "floating-pavilion",
    hallId: "oasis",
    number: "03",
    title: "במת המים • The Water Altar",
    subtitle: "חופה ארכיטקטונית צפה על המים",
    label: "חופה ארכיטקטונית צפה על המים",
    location: "רחבת הבריכה המרכזית",
    year: "2026",
    image: "images/projects/oasis-04.webp",
  },
  {
    id: "sunset-ceremony",
    hallId: "oasis",
    number: "04",
    title: "קבלת פנים שקיעה • Sunset Reception",
    subtitle: "מתחם טקסים פנורמי תחת כיפת השמיים",
    label: "מתחם טקסים פנורמי תחת כיפת השמיים",
    location: "חוקות השמיים",
    year: "2026",
    image: "images/projects/oasis-06.webp",
  },
  {
    id: "desert-banquet",
    hallId: "oasis",
    number: "05",
    title: "משתה המדבר • Desert Banquet",
    subtitle: "סעודת אבירים ארוכה בעיצוב ארצי מתוחכם",
    label: "סעודת אבירים ארוכה בעיצוב ארצי מתוחכם",
    location: "מתחם הקולונדה",
    year: "2026",
    image: "images/projects/oasis-08.webp",
  },
  {
    id: "curated-details",
    hallId: "oasis",
    number: "06",
    title: "פרטי האומנות • Curated Details",
    subtitle: "ניואנסים מעודנים של עושר וטבע",
    label: "ניואנסים מעודנים של עושר וטבע",
    location: "פנים וחוץ",
    year: "2026",
    image: "images/projects/oasis-10.webp",
  },
  {
    id: "grand-arrival",
    hallId: "oasis",
    number: "07",
    title: "כיכר הבואים • The Grand Arrival",
    subtitle: "רחבת אבן רחבה תחת חזית האולם המוארת",
    label: "רחבת אבן רחבה תחת חזית האולם המוארת",
    location: "כיכר הכניסה הראשית",
    year: "2026",
    image: "images/projects/oasis-09.webp",
  },
  {
    id: "stone-promenade",
    hallId: "oasis",
    number: "08",
    title: "טיילת האבן • The Stone Promenade",
    subtitle: "בר עצים וטרסות בין עצי זית עתיקים",
    label: "בר עצים וטרסות בין עצי זית עתיקים",
    location: "מתחם החוץ והבר המרכזי",
    year: "2026",
    image: "images/projects/oasis-05.webp",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // HALL 2: LUMINA SANCTUARY (היכל דמדומים / מתחם הספירות הזוהרות)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lumina-canal",
    hallId: "lumina",
    number: "01",
    title: "תעלת האורות • The Dusk Canal",
    subtitle: "תמונת המדבר וחוג הספירות הזוהרות המשתקפות",
    label: "תמונת המדבר וחוג הספירות הזוהרות המשתקפות",
    location: "ציר המים המרכזי",
    year: "2026",
    image: "images/projects/lumina-01.webp",
  },
  {
    id: "floating-harmony",
    hallId: "lumina",
    number: "02",
    title: "התרחבות הספירות • Floating Harmony",
    subtitle: "ספירות המדבר הצפות ומפזרות זוהר",
    label: "ספירות המדבר הצפות ומפזרות זוהר",
    location: "מתחם הספירות הזוהרות",
    year: "2026",
    image: "images/projects/lumina-02.webp",
  },
  {
    id: "dusk-reflection",
    hallId: "lumina",
    number: "03",
    title: "שער הדמדומים • The Dusk Portal",
    subtitle: "טבילה קוסמית של מים והשתקפויות שמיים",
    label: "טבילה קוסמית של מים והשתקפויות שמיים",
    location: "הבריכה הדרומית",
    year: "2026",
    image: "images/projects/lumina-03.webp",
  },
  {
    id: "glowing-horizons",
    hallId: "lumina",
    number: "04",
    title: "אופקים זוהרים • Glowing Horizons",
    subtitle: "נוף הרי המדבר מאחורי כדורי הזוהר",
    label: "נוף הרי המדבר מאחורי כדורי הזוהר",
    location: "חמוקי הדיונה",
    year: "2026",
    image: "images/projects/lumina-04.webp",
  },
  {
    id: "lumina-banquet",
    hallId: "lumina",
    number: "05",
    title: "הגסטרונומיה הזוהרת • Lumina Feast",
    subtitle: "חווית סעודה מוקפת בספירות חמימות",
    label: "חווית סעודה מוקפת בספירות חמימות",
    location: "מתחם האקוודוקט השקט",
    year: "2026",
    image: "images/projects/lumina-05.webp",
  },
  {
    id: "celestial-textures",
    hallId: "lumina",
    number: "06",
    title: "חלקיקי הזוהר • Celestial Textures",
    subtitle: "פרטי העיצוב המהפנטים של האולם השני",
    label: "פרטי העיצוב המהפנטים של האולם השני",
    location: "חלל פנים וחוץ בעיצוב ספירות",
    year: "2026",
    image: "images/projects/lumina-06.webp",
  },
  {
    id: "twin-orbs",
    hallId: "lumina",
    number: "07",
    title: "הספירות התאומות • The Twin Orbs",
    subtitle: "שתי ספירות זוהרות מרחפות מעל חולות המדבר",
    label: "שתי ספירות זוהרות מרחפות מעל חולות המדבר",
    location: "מישור המדבר הפתוח",
    year: "2026",
    image: "images/projects/lumina-07.webp",
  },
  {
    id: "infinity-mirror",
    hallId: "lumina",
    number: "08",
    title: "מראת האינסוף • The Infinity Mirror",
    subtitle: "בריכת אינסוף שקטה מול אופק הדיונות",
    label: "בריכת אינסוף שקטה מול אופק הדיונות",
    location: "טרסת הבריכה הצפונית",
    year: "2026",
    image: "images/projects/lumina-08.webp",
  },
];

export function getProjectsByHall(hallId: "oasis" | "lumina"): ProjectWithColors[] {
  const colorMap = extractedColors as Record<string, ExtractedColors>;
  return projectsData
    .filter((p) => p.hallId === hallId)
    .map((p) => ({ ...p, colors: colorMap[p.image] ?? FALLBACK_COLORS }));
}
