// Regenerate the GAMOS favicon set from the standalone emblem logo.
// Source already has a transparent background; we trim it to a tight square and emit the
// icon set on a TRANSPARENT canvas (no background tile).
// Run: node scripts/make-favicon.mjs   (sharp is a repo dependency)
import sharp from "sharp";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SRC = resolve(ROOT, "../GAMOS-DOCS/תמונות לאנימציית האתר/לוגו/לוגו_.png");
const ASSETS = resolve(ROOT, "assets");

const PAD_RATIO = 0.04; // small inset so the outer rays don't touch the icon edge

// 1. Trim the transparent margins to a tight bound, then pad to a centred square.
const trimmed = await sharp(SRC).trim().toBuffer();
const t = await sharp(trimmed).metadata();
const side = Math.max(t.width, t.height);
const emblemSquare = await sharp(trimmed)
  .extend({
    top: Math.round((side - t.height) / 2),
    bottom: side - t.height - Math.round((side - t.height) / 2),
    left: Math.round((side - t.width) / 2),
    right: side - t.width - Math.round((side - t.width) / 2),
    background: { r: 0, g: 0, b: 0, alpha: 0 },
  })
  .png()
  .toBuffer();

// Transparent square tile with the emblem inset.
async function tile(size) {
  const inner = Math.round(size * (1 - PAD_RATIO * 2));
  const mark = await sharp(emblemSquare)
    .resize(inner, inner, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .toBuffer();
  const off = Math.round((size - inner) / 2);
  return sharp({
    create: { width: size, height: size, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
  })
    .composite([{ input: mark, top: off, left: off }])
    .png()
    .toBuffer();
}

// 2. PNG icon set.
const sizes = {
  "favicon-16.png": 16, // added 2026-07-13 (conversion pass — full icon set)
  "favicon-32.png": 32,
  "apple-touch-icon.png": 180,
  "icon-192.png": 192,
  "icon-512.png": 512,
};
for (const [name, size] of Object.entries(sizes)) {
  await sharp(await tile(size)).toFile(resolve(ASSETS, name));
  console.log("wrote", name, `${size}x${size}`);
}

// 2b. /favicon.ico at the repo ROOT (added 2026-07-13) — legacy clients and
// some crawlers request it blindly. ICO container with embedded PNG entries
// (valid since Vista); hand-rolled ~20 lines so we add no dependency (§2).
async function buildIco(pngSizes) {
  const images = [];
  for (const s of pngSizes) images.push({ size: s, buf: await tile(s) });
  const HEADER = 6;
  const DIR = 16;
  let offset = HEADER + DIR * images.length;
  const header = Buffer.alloc(HEADER);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(images.length, 4);
  const parts = [header];
  const blobs = [];
  for (const { size, buf } of images) {
    const entry = Buffer.alloc(DIR);
    entry.writeUInt8(size >= 256 ? 0 : size, 0); // width
    entry.writeUInt8(size >= 256 ? 0 : size, 1); // height
    entry.writeUInt8(0, 2);       // palette colors
    entry.writeUInt8(0, 3);       // reserved
    entry.writeUInt16LE(1, 4);    // color planes
    entry.writeUInt16LE(32, 6);   // bits per pixel
    entry.writeUInt32LE(buf.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += buf.length;
    parts.push(entry);
    blobs.push(buf);
  }
  return Buffer.concat([...parts, ...blobs]);
}
await writeFile(resolve(ROOT, "favicon.ico"), await buildIco([16, 32, 48]));
console.log("wrote favicon.ico (16+32+48 PNG-in-ICO) at repo root");

// 3. favicon.svg — emblem embedded as a 64px base64 PNG on transparent bg so the
//    primary <link rel="icon" type="image/svg+xml"> matches the PNG set. No HTML edits.
const b64 = (await tile(64)).toString("base64");
const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GAMOS favicon — gold sunburst emblem ("G"), transparent background.
  Generated by scripts/make-favicon.mjs from GAMOS-DOCS/.../לוגו/לוגו_.png.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="גאמוס">
  <title>גאמוס</title>
  <image width="64" height="64" href="data:image/png;base64,${b64}"/>
</svg>
`;
await writeFile(resolve(ASSETS, "favicon.svg"), svg);
console.log("wrote favicon.svg");
